name: Auto Build and Move Artifacts

on:
  pull_request:
    types: [closed]

jobs:
  build-and-move:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Build project
        run: node ./scripts/build.js
        
      - name: Create preview directory
        run: mkdir -p preview/dist
        
      - name: Move build artifacts
        run: mv dist/* preview/dist/
        
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: update preview build"
          title: "Update Preview Build"
          body: "自动更新预览构建文件"
          branch: "auto-preview-update"
          delete-branch: true
          
      - name: Auto-merge Pull Request
        run: |
          sleep 180
          gh pr merge --auto --merge "auto-preview-update"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}        run: mv dist/* preview/dist/