name: Auto Build and Deploy

on:
  pull_request:
    types: [closed]

jobs:
  build-and-deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Build project
        run: node ./scripts/build.js
        
      - name: Setup Pages
        uses: actions/configure-pages@v3
        # TODO: 配置自定义域名
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: 'preview'
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
